from . import external_invoice
from . import contract
from . import medical_attention_order
from . import medical_diagnostic
from . import medical_procedure
from . import medical_liquidation
from . import partner
from . import medical_speciality
from . import medical_procedure_type
from . import company
from . import res_config_settings
from . import medical_relationship
from . import medical_beneficts
from . import account_move
from . import report_invoice_xlsx
